---
apiVersion: v1
kind: Secret
metadata:
  name: utherp0-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/utherp0-backend-gitops
